### ISSUE TITLE
MODULE_NOT_FOUND error with resume-cli version 3

### ISSUE THREAD

**Issue by mpostument** [phoinixi/jsonresume-theme-stackoverflow#54]
Hello, 

Started to get this error when did update to resumecli v3
```shell
Run resume export resume.pdf -t jsonresume-theme-stackoverflow
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './init'
Require stack:
- /opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/main.js:6:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/main.js'
  ]
}
Error: Process completed with exit code 1.
```
Any ideas on how to fix it?

**Comment by mpostument** [comment]
The new version of resume-cli fixed issue 
https://github.com/jsonresume/resume-cli/releases/tag/v3.0.3

**Comment by mpostument** [comment]
But now build is failing with 
```shell
TypeError: Cannot read property '0' of undefined
    at _default (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/render-html.js:23:16)
    at /opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/export-resume.js:107:48
    at createPdf (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/export-resume.js:128:5)
    at module.exports (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/export-resume.js:44:5)
    at Command.<anonymous> (/opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/main.js:67:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async /opt/hostedtoolcache/node/14.15.1/x64/lib/node_modules/resume-cli/build/main.js:79:3 `createPdf` errored out
```

**Comment by mpostument** [comment]
fixed with https://github.com/jsonresume/resume-cli/releases/tag/v3.0.4
